In [15]:
import numpy as np

In [16]:
# Para criar uma matriz unidimensional

mt = np.array([12, 34, 26, 18, 10]) # Array passado como argumento do método "array()" de "numpy"
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [17]:
# Para criar uma matriz com tipos específicos
# Criar um array do tipo float de 64 bits

mtfloat = np.array([1, 2, 3], dtype = np.float64)
print(mtfloat)
print(type(mtfloat))

[1. 2. 3.]
<class 'numpy.ndarray'>


In [18]:
# Para criar uma matriz com tipos específicos
# Criar um array do tipo int de 32 bits

mtint = np.array([1, 2, 3], dtype = np.int32)
print(mtint)
print(type(mtint))

[1 2 3]
<class 'numpy.ndarray'>


In [19]:
# Para mudar o tipo do array de float para int

mt_new = np.array([1.4, 3.6, -5.1, 9.42, 4.999999])
print(mt_new)

mt_new_int = mt_new.astype(np.int32) # Quando transformamos de float para int, os valores são truncados
print(mt_new_int)

[ 1.4       3.6      -5.1       9.42      4.999999]
[ 1  3 -5  9  4]


In [20]:
# Para mudar o tipo do array de int para float

mt_int = np.array([1, 2, 3, 4])
print(mt_int)

mt_float = mt_int.astype(np.float64)
print(mt_float)

[1 2 3 4]
[1. 2. 3. 4.]


In [21]:
# Para criar uma matriz bidimensional

mt_bi = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(mt_bi)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
# Para criar arrays não inicializados tipificados
# O método "empty()" sugere que o array não foi inicializado, não que é vazio

vazio = np.empty([3,2], dtype = int)
print(vazio)

[[         0 1072693248]
 [         0 1073741824]
 [         0 1074266112]]


In [23]:
# Para criar uma matriz 4x3 de zeros

mt_zeros = np.zeros([4,3])
print(mt_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [24]:
# Para criar uma matriz 5x7 de 1

mt_ones = np.ones([5,7])
print(mt_ones)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [25]:
# Para criar uma matriz identidade de ordem 5

mt_id = np.eye(5)
print(mt_id)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [28]:
# Para criar um array de valores aleatórios entre 0 e 1 de ordem 5

ar_rd = np.random.random((5))
print(ar_rd)

[0.7364112  0.56722853 0.23136197 0.27859836 0.32700221]


In [32]:
# Para criar um array de valores aleatórios distribuídos normalmente contendo negativos

ar_dn = np.random.randn((5))
print(ar_dn)

[-0.93590444 -1.29751459  0.70196278  0.15597835  1.28044454]


In [31]:
# Para criar uma matriz 3x4 de valores aleatórios

mt_rd = 10 * np.random.random((3,4))
print(mt_rd)

[[1.43487666 6.92861246 8.62106677 2.41271301]
 [1.73087679 6.23506775 5.6427059  7.23538689]
 [2.98404378 2.78693388 1.07478963 7.6058954 ]]


In [39]:
# Outras formas de gerar aleatórios

# Uso de semente
# Em geral, quando temos processos estocásticos (que possuem alguma forma de aleatoriedade, não determinísticos) 
# é necessário repetir o experimento, repetir os números aleatórios da mesma forma que eles foram gerados.
# Sendo assim, a utilização de sementes é uma alternativa para que os números aleatórios gerados sejam sempre os mesmos.

gnr = np.random.default_rng(1) # Nesse caso, o "1" é a semente
rd = gnr.random(3) # Serão gerados 3 números aleatórios
print(rd)

[0.51182162 0.9504637  0.14415961]


In [40]:
# Para gerar uma matriz 3x4 de números aleatórios inteiros até 10 usando semente

rd_int = gnr.integers(10, size=(3,4))
print(rd_int)

[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [50]:
# unique() para remover repetições

j = np.array([11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 18, 19, 20])
j1 = np.unique(j)
print(j1)

[11 12 13 14 15 16 17 18 19 20]


In [67]:
# Propriedades da matriz

k = np.array([[17, 22, 43], [27, 25, 14], [15, 24, 32]])
print(k)
print(k[0][1]) # Mostra um elemento específico da matriz # A indexação é iniciada em 0
print(k.shape) # Mostra a dimensão da matriz k

[[17 22 43]
 [27 25 14]
 [15 24 32]]
22
(3, 3)


In [68]:
# Funções Matemáticas

# Mostra o maior valor da matriz k

print(k.max())

# Mostra o menor valor da matriz k

print(k.min())

# Mostra a soma dos valores da matriz k

print((k.sum()))

# Mostra o valor da média dos valores da matriz k

print(k.mean())

# Mostra o valor do desvio padrão (standard deviation) dos valores da matiz k

print(k.std())

43
14
219
24.333333333333332
8.615231988880057


In [69]:
# Funções universais, aplicadas a todos os elementos

# Mostra o valor da raiz quadrada de todos elementos

k1 = np.array([1, 4, 9, 16, 25, 36])
print(np.sqrt(k1))

# Mostra o valor do exponencial de todos elementos

print(np.exp(k1))

[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [70]:
# Extração de elementos

m = np.array([1, 2, 3, 4, 5, 6])

# Mostra o elemento da posição 2

print(m[1])
print("-------")

# Mostra o array criado a partir da posição 0, dois elementos

print(m[0:2]) # Em um intervalo definido, o Python ignora o último valor
print("-------")

# Mostra o array criado a partir da posição 2
# Até todo o restante do array

print(m[1:])
print("-------")

# Mostra o array criado a partir da antepenúltima
# Posição até o final

print(m[-3:])

2
-------
[1 2]
-------
[2 3 4 5 6]
-------
[4 5 6]


In [71]:
# Extração de linhas e colunas

l = np.array([[4, 5], [6, 1], [7, 4]])
print(l)
print("-------")

# Primeira linha, todas as colunas

l_linha_1 = l[0, :]
print(l_linha_1)
print("-------")

# Segunda linha

l_linha_2 = l[1, :]
print(l_linha_2)
print("-------")

# Terceira linha

l_linha_3 = l[2, :]
print(l_linha_3)
print("-------")

# Todas as linhas, primeira coluna

l_coluna_1 = l[:, 0]
print(l_coluna_1)
print("-------")

# Todas as linhas, segunda coluna

l_coluna_2 = l[:, 1]
print(l_coluna_2)

[[4 5]
 [6 1]
 [7 4]]
-------
[4 5]
-------
[6 1]
-------
[7 4]
-------
[4 6 7]
-------
[5 1 4]


In [72]:
# Adição e multiplicação de matrizes

n = np.array([[1, 2], [3, 4]])
o = np.array([[1, 1], [1, 1]])
res1 = n + o

print(res1)
print("-------")

res2 = n * o

print(res2)
print("-------")

p = np.array([[1, 2], [3, 4], [5, 6]])
q = np.array([[2, 1]])

print(p + q)

[[2 3]
 [4 5]]
-------
[[1 2]
 [3 4]]
-------
[[3 3]
 [5 5]
 [7 7]]


In [73]:
# Rearranja um conjunto de 15 elementos de 0 a 14 
# em 3 linhas e 5 colunas.

f = np.arange(15).reshape((3, 5))
print(f)
print("-------")

# Mostra a matriz transposta entre linha e coluna

s = f.T # "T" para a obtenção da matriz transposta
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [74]:
# Outra forma de fazer transposição, mesmo resultado

r = np.arange(15).reshape((3, 5))
print(r)
print("-------")

s = r.transpose((1,0))
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [75]:
# Expressões lógicas
# Usando where

# Criando matriz com valores aleatórios positivos e negativos

v = np.random.randn(4, 4)
print(v)

# Criando matriz com valores booleanos baseados no array v

x = (v > 0)
print(x)

# Criando matriz com valores -1 e 1 baseados nos valores do array x

z = np.where(x > 0, 1, -1)
print(z)


[[ 0.06996028 -1.32427742  0.49006833  0.08437162]
 [-2.72979424 -1.40512456 -0.2421071  -0.79664992]
 [-2.05434643  0.61605674  0.48119571  0.32294138]
 [ 2.60922164  0.45083512  0.09332648 -0.72463768]]
[[ True False  True  True]
 [False False False False]
 [False  True  True  True]
 [ True  True  True False]]
[[ 1 -1  1  1]
 [-1 -1 -1 -1]
 [-1  1  1  1]
 [ 1  1  1 -1]]
